Error in file(file, "rt") : cannot open the connection
Calls: read.csv -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'spills_2010_2019.csv.csv': No such file or directory
Execution halted
